version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: job_seek_mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: job-seek
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: job_seek_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  redis_data:
